spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    #localhost
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    #render
#    url: jdbc:postgresql://dpg-d0qnjijuibrs73ep03qg-a:5432/my_postgres_i2dp
#    username: my_postgres_i2dp_user
#    password: Ec4bEN5zQoVAqkwJSbLtw065ovYQNkSW
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 53633076130-3u5i0orv2aui4cl34ebc7hao2p400aq3.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - openid
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub

logging:
  level:
    org.springframework.security: TRACE